# NYU depth config

# Finetune from:
finetune: '/root/datasets/jake/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c (1).pth' # Change me

# Input tasks
in_domains: rgb
use_mask_valid: False # Requires "task" mask_valid to be saved to disk

# Architecture
model: multivit_base
patch_size: 16
num_global_tokens: 1
drop_path_encoder: 0.0
output_adapter: convnext
decoder_dim: 6144
decoder_preds_per_patch: 64
decoder_depth: 4

# Train
loss: berhu
epochs: 2000
opt: adamw
lr: 0.0001 # = 1e-4
warmup_lr: 0.000001 # = 1e-6
min_lr: 0.
warmup_epochs: 100
batch_size: 16
input_size: 256
layer_decay: 0.75
weight_decay: 0.00001 # 1e-4

# Augmentation
aug_name: nyu-augs

#SGT
prompt_mode : deep
prompt_pool : True
prompt_shallow : False
prompt_deep : True
top_k : 5
size : 5
length : 5 
task_specific_prompt_length : 200
not_self_attn : False
use_prompt_mask : True

# Data info
data_path: '/root/datasets/jake/NYUv2_Dataset/NYUv2/NYUv2/train' # Change me
eval_data_path: '/root/datasets/jake/NYUv2_Dataset/NYUv2/NYUv2/test' # Change me
color_augs: True
dataset_name: nyu
dist_eval: True
eval_freq: 10
standardize_depth: False

# Misc.
find_unused_params: True

# Wandb and logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: 'multimae-finetune-depth'
wandb_entity: null # Change if needed
wandb_run_name: 'ft_nyu_2000e_multimae-b'
log_images_wandb: False
log_images_freq: 250
output_dir: '/output/finetune/depth/ft_nyu_2000e_multimae-b' # Change if needed
