# NYU semseg config

# Finetune from:
finetune:  "/root/datasets/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c (1).pth"

# Input tasks
in_domains: rgb-depth
seed : 0

# Architecture
model: multivit_base
patch_size: 16
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: convnext
decoder_dim: 6144
decoder_preds_per_patch: 16
decoder_depth: 4

# Train
epochs: 128
opt: adamw
lr: 0.000025 # = 1.5e-5
warmup_lr: 0.00000025 # = 1e-6
min_lr: 0.
warmup_epochs: 1
batch_size: 4
input_size: 512
layer_decay: 0.75
weight_decay: 0.00001
open_layer : None

# Augmentation
aug_name: simple

# Data info
data_path: "/root/datasets/ADE20K/train"
eval_data_path: "/root/datasets/ADE20K/test" # Change me
num_classes: 150
dataset_name: ade20k
dist_eval: True
seg_reduce_zero_label: True
eval_freq: 4

# Misc.
find_unused_params: False

#prompt
prompt_mode : deep
prompt_pool : True
prompt_shallow : False
prompt_deep : True
top_k : 5
size : 5
length : 5 
task_specific_prompt_length : 128
not_self_attn : False
use_prompt_mask : True

# Wandb and logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: 'ADE20K-RGB-Test'
wandb_entity: null # Change if needed
wandb_run_name: 'ADE20K-prompt=128'
log_images_wandb: False
log_images_freq: 20
output_dir: '/root/workspace/Results/ADE20K(512)-prompt=128'