# NYU semseg config

# Finetune from:
# finetune: "/root/datasets/mae-b_dec512d8b_1600e_multivit-c477195b.pth"
finetune:  "/root/datasets/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c (1).pth"

# Input tasks
in_domains: rgb-depth
seed : 0

# Architecture
model: multivit_base
patch_size: 16
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: segmenter
decoder_dim: 768
decoder_preds_per_patch: 16
decoder_depth: 2

# Train
epochs: 300
opt: adamw
lr: 0.000005 # = 1.5e-5
warmup_lr: 0.00000005 # = 1e-6
min_lr: 0.
warmup_epochs: 5
batch_size: 1
input_size: 640
layer_decay: 0.75
weight_decay: 0.00001
open_layer : None

# Augmentation
aug_name: simple

# Data info
data_path: "/root/datasets/srgbd/train"
eval_data_path: "/root/datasets/srgbd/test" # Change me
num_classes: 37
dataset_name: sun
dist_eval: False
seg_reduce_zero_label: True
eval_freq: 10

# Misc.
find_unused_params: True

#prompt
prompt_mode : deep
prompt_pool : True
prompt_shallow : False
prompt_deep : True
top_k : 5
size : 5
length : 5 
task_specific_prompt_length : 200
not_self_attn : False
use_prompt_mask : True

# Wandb and logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: 'SEGMENTER TEST'
wandb_entity: null # Change if needed
wandb_run_name: 'MULTIMAE-SUN'
log_images_wandb: False
log_images_freq: 20
output_dir: '/root/workspace/Results/MULTIMAE-SUN'