# NYU semseg config

# Finetune from:
finetune:  "/content/drive/MyDrive/MultiMAE/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c (1).pth"

# Input tasks
in_domains: rgb

# Architecture
model: multivit_base
patch_size: 16
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: convnext
decoder_dim: 6144
decoder_preds_per_patch: 16
decoder_depth: 4

# Train
epochs: 100
opt: adamw
lr: 0.0001 # = 1e-4
warmup_lr: 0.000001 # = 1e-6
min_lr: 0.
warmup_epochs: 1
batch_size: 5
input_size: 640
layer_decay: 0.75

# Augmentation
aug_name: simple

# Data info
data_path: "/content/drive/MyDrive/NYUv2/train"
eval_data_path: "/content/drive/MyDrive/NYUv2/test"# Change me
num_classes: 40
dataset_name: nyu
dist_eval: True
seg_reduce_zero_label: True
eval_freq: 200

# Misc.
find_unused_params: False

#prompt
prompt_mode : shallow
prompt_pool : True
prompt_shallow : True
prompt_deep : False
top_k : 5
size : 10
length : 5

# Wandb and logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project:  'multimae-multi-l2p-shallow'
wandb_entity: null # Change if needed
wandb_run_name: 'ft_nyu_200e_multimae-b_rgb'
log_images_wandb: True
log_images_freq: 20
output_dir: 'output/finetune/semseg/nyu/ft_nyu_200e_multimae-b_rgb'