# Finetune from:
finetune:  '/root/' # Change me

# Input tasks
in_domains: rgb-depth
seed : 0

# Architecture
model: multivit_base
patch_size: 16
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: convnext # Change me
decoder_dim: 6144
decoder_preds_per_patch: 16
decoder_depth: 4

# Train
epochs: 350
opt: Adamw
lr: 0.00002
warmup_lr: 0.0000002
min_lr: 0.
warmup_epochs: 5
batch_size: 1
input_size: 640
layer_decay: 0.75
weight_decay: 0.00001
open_layer : None

# Augmentation
aug_name: simple

# Data info
data_path: '/root/datasets/' # Change me
eval_data_path: '/root/datasets/'
num_classes: 40
dataset_name: nyu   
dist_eval: True
seg_reduce_zero_label: True
eval_freq: 10

# Misc.
find_unused_params: True

#prompt
task_specific_prompt_length : 200

# Wandb and logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: 'TEST'
wandb_entity: null # Change if needed
wandb_run_name: 'TEST'
log_images_wandb: False
log_images_freq: 1
output_dir: '/root/'